# Default values for mdviewer.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: deneasta/mdviewer
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "fc7202a41c83a7d2525494aa6d6559abb6dcfa05"

namespace: mdviewer

service:
  type: NodePort
  port: 80
  targetPort: 8080
  nodePort: 30080

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi
