# Default values for mdviewer.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: deneasta/mdviewer
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "8e4f266095b32ca9b9dcca2bb498ae03a4d7386a"

namespace: mdviewer

service:
  type: NodePort
  port: 80
  targetPort: 8080
  nodePort: 30080

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi
