apiVersion: v1
kind: Service
metadata:
  name: mdviewer-svc
  namespace: mdviewer
spec:
  selector:
    app: mdviewer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080
  type: NodePort
