apiVersion: apps/v1
kind: Deployment
metadata:
  name: mdviewer
  namespace: mdviewer
  labels:
    app: mdviewer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mdviewer
  template:
    metadata:
      labels:
        app: mdviewer
    spec:
      containers:
      - name: mdviewer
        image: deneasta/mdviewer:759e96a8ef1f74388efad6a302e2ffb2cdd8a3cb
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
