apiVersion: apps/v1
kind: Deployment
metadata:
  name: mdviewer
  namespace: mdviewer
  labels:
    app: mdviewer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mdviewer
  template:
    metadata:
      labels:
        app: mdviewer
    spec:
      containers:
      - name: mdviewer
        image: deneasta/mdviewer:8e4f266095b32ca9b9dcca2bb498ae03a4d7386a
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
